=== katerynagit/project.com/faktura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="unqualified">

    <xs:element name="FakturaVAT">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="NumerFaktury" type="xs:string"/>
                <xs:element name="DataWystawienia" type="xs:date"/>

                <xs:element name="Sprzedawca">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nazwa" type="xs:string"/>
                            <xs:element name="Adres" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Nabywca">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Imie" type="xs:string"/>
                            <xs:element name="Nazwisko" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Pozycje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Pozycja" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Lp" type="xs:integer"/>
                                        <xs:element name="NazwaUslugi" type="xs:string"/>
                                        <xs:element name="Ilosc" type="xs:decimal"/>
                                        <xs:element name="CenaJednostkowa" type="xs:decimal"/>
                                        <xs:element name="Wartosc" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== katerynagit/project.com/faktura.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="faktura.xsl"?>

<FakturaVAT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="faktura.xsd">

    <NumerFaktury>FV/2025/001</NumerFaktury>
    <DataWystawienia>16.11.2025</DataWystawienia>

    <Sprzedawca>
        <Nazwa>Firma WebStudio</Nazwa>
        <Adres>Warszawa, ul. Jagielońska 10, 03-721</Adres>
    </Sprzedawca>

    <Nabywca>
        <Imie>Aleksandr</Imie>
        <Nazwisko>Nowak</Nazwisko>
         <Adres>Wrocław, ul. Inżynierska 10, 53-227</Adres>
    </Nabywca>

    <Pozycje>
        <Pozycja>
            <Lp>1</Lp>
            <NazwaUslugi>Projekt strony www.project5.com</NazwaUslugi>
            <Ilosc>1</Ilosc>
            <CenaJednostkowa>2500.00</CenaJednostkowa>
            <Wartosc>2500.00</Wartosc>
        </Pozycja>

        <Pozycja>
            <Lp>2</Lp>
            <NazwaUslugi>Administracja serwerem</NazwaUslugi>
            <Ilosc>3</Ilosc>
            <CenaJednostkowa>150.00</CenaJednostkowa>
            <Wartosc>450.00</Wartosc>
        </Pozycja>

        <Pozycja>
            <Lp>3</Lp>
            <NazwaUslugi>Wsparcie techniczne</NazwaUslugi>
            <Ilosc>5</Ilosc>
            <CenaJednostkowa>80.00</CenaJednostkowa>
            <Wartosc>400.00</Wartosc>
        </Pozycja>
    </Pozycje>
</FakturaVAT>
